name: smsmock
version: 0.1.0
description: 'Server which provides mock of SMS gateway for development, QA or demo environment.'
author: Roman Shamritskiy <roman@litgroup.ru>
homepage: https://github.com/litgroup/mock-sms-server

environment:
  sdk: '^1.15.0'

dependencies:
  di: '^3.3.8'

dev_dependencies:
  test: '^0.12.13'

transformers:
- $dart2js:
    $exclude: "bin/server.dart"
    minify: true
